-- Role: brontosaur
-- DROP ROLE IF EXISTS brontosaur;

CREATE ROLE brontosaur WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  CREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:6V7+Hfj8oUwCmf3A/Vilwg==$ROth0JryyqiyPcNQPNAtHeUHwi4TVuAgjz7d6Yn2kAA=:WP38Bt8vGXtpiIp/qOwWuzIJserslZydk8ju0ixUSZI=';